# Generated by Django 5.2.4 on 2025-07-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='image_url',
            field=models.ImageField(upload_to='static/news_images/'),
        ),
    ]
