# Generated by Django 5.2.4 on 2025-07-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspost_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='image_url',
            field=models.ImageField(upload_to='news_images/'),
        ),
    ]
